const SET_PAGE = "SET_PAGE";
const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";

// Inside Events.js
const SET_CURRENT_DATE = "SET_CURRENT_DATE";

// Inside Home.js
const SET_HOME_GROUPS = "SET_HOME_GROUPS";
const SET_CURRENT_GROUP = "SET_CURRENT_GROUP";
const SET_GROUP_LAST_UPDATED = "SET_GROUP_LAST_UPDATED";


//random acitons
const INIT = "INIT";
export{
    SET_PAGE,
    INIT,
    SET_NOTIFICATIONS,
    SET_CURRENT_DATE,
    SET_HOME_GROUPS,
    SET_CURRENT_GROUP,
    SET_GROUP_LAST_UPDATED
}